#!/bin/sh

cd "$(dirname "$0")"

rm -rf build >/dev/null 2>&1
mkdir build
cd build && \
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DKDE_INSTALL_LIBDIR=lib \
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
    -DBUILD_TESTING=OFF \
    .. && \
make -j4 && \
sudo make install
