# - Try to find FFMpeg libraries
# Once done this will define
#  FFMPEG_FOUND - System has LibFFMPEG
#  FFMPEG_VERSION - LibFFMPEG version
#  FFMPEG_INCLUDE_DIRS - The LibFFMPEG include directories
#  FFMPEG_LIBRARIES - The libraries needed to use LibFFMPEG
#  FFMPEG_DEFINITIONS - Compiler switches required for using LibFFMPEG

find_package(PkgConfig)
pkg_check_modules(PC_FFMPEG_AVCODEC QUIET libavcodec)
pkg_check_modules(PC_FFMPEG_AVFORMAT QUIET libavformat)
pkg_check_modules(PC_FFMPEG_AVUTIL QUIET libavutil)
set(FFMPEG_DEFINITIONS ${PC_FFMPEG_CFLAGS_OTHER})
set(FFMPEG_VERSION ${PC_FFMPEG_VERSION})

find_path(FFMPEG_INCLUDE_DIR libavcodec/avcodec.h
	HINTS
		${PC_FFMPEG_AVCODEC_INCLUDEDIR} ${PC_FFMPEG_AVCODEC_INCLUDE_DIRS}
		${PC_FFMPEG_AVFORMAT_INCLUDEDIR} ${PC_FFMPEG_AVFORMAT_INCLUDE_DIRS}
		${PC_FFMPEG_AVUTIL_INCLUDEDIR} ${PC_FFMPEG_AVUTIL_INCLUDE_DIRS}
	PATH_SUFFIXES ffmpeg)

find_library(FFMPEG_AVCODEC_LIBRARY
	NAMES avcodec
	HINTS
		${PC_FFMPEG_AVCODEC_LIBDIR} ${PC_FFMPEG_AVCODEC_LIBRARY_DIRS})

find_library(FFMPEG_AVFORMAT_LIBRARY
	NAMES avformat
	HINTS
		${PC_FFMPEG_AVFORMAT_LIBDIR} ${PC_FFMPEG_AVFORMAT_LIBRARY_DIRS})

find_library(FFMPEG_AVUTIL_LIBRARY
	NAMES avutil
	HINTS
		${PC_FFMPEG_AVUTIL_LIBDIR} ${PC_FFMPEG_AVUTIL_LIBRARY_DIRS})

find_library(FFMPEG_SWRESAMPLE_LIBRARY
	NAMES swresample
	HINTS
		${PC_FFMPEG_SWRESAMPLE_LIBDIR} ${PC_FFMPEG_SWRESAMPLE_LIBRARY_DIRS})

set(FFMPEG_LIBRARIES ${FFMPEG_AVCODEC_LIBRARY} ${FFMPEG_AVFORMAT_LIBRARY} ${FFMPEG_AVUTIL_LIBRARY} ${FFMPEG_SWRESAMPLE_LIBRARY})
set(FFMPEG_INCLUDE_DIRS ${FFMPEG_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set FFMPEG_FOUND to TRUE if all listed variables are TRUE
find_package_handle_standard_args(FFMPEG
	REQUIRED_VARS FFMPEG_AVCODEC_LIBRARY FFMPEG_AVFORMAT_LIBRARY FFMPEG_AVUTIL_LIBRARY FFMPEG_SWRESAMPLE_LIBRARY FFMPEG_LIBRARY FFMPEG_INCLUDE_DIR)

mark_as_advanced(FFMPEG_INCLUDE_DIR FFMPEG_LIBRARY)
